:revnumber: {project-version}

= {name}
{description}
:toc: left

== Runtime Dependencies

* Java >= `{java-version}`
* Spring Boot >= `{spring-boot-version}`

The module was compiled against :

* Spring Boot Actuator = `{spring-boot-version}`

== Installation

[source,xml,subs="verbatim,attributes"]
.Using the library
----
    <dependency>
        <groupId>{project-groupId}</groupId>
        <artifactId>{project-artifactId}</artifactId>
        <version>{project-version}</version>
    </dependency>
----
The library contains all required dependencies, including `spring-boot-starter-actuator v{spring-boot-version}`.

== Usage

=== Using the @Metrics annotation
[source,java]
.As class level annotation
----

include::{project-basedir}/src/test/java/de/dm/infrastructure/metrics/testfixtures/WithMetricClassAnnotation.java[tags=usage]
----
When used at the class level, metrics for all public methods of the annotated class are collected.
[source,java]
.As method level annotation
----

include::{project-basedir}/src/test/java/de/dm/infrastructure/metrics/testfixtures/WithMetricMethodAnnotation.java[tags=usage]
----
When used at the method level, metrics are collected for annotated methods only.

== Configuration

=== Default configuration

The library contains a default <micrometer-registry-statsd> which is already configured for default telnet communication.

The library also contains a set of default metrics which are provided from the <spring-boot-actuator>

Further informations about micrometer can be found here https://micrometer.io/[micrometer]


